// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyABT1Iy6MUnGPndHHlNJ2zeYoigpWRSx4o',
    appId: '1:448521017553:android:04fbad20c62652d034cdf0',
    messagingSenderId: '448521017553',
    projectId: 'lyne-9532c',
    storageBucket: 'lyne-9532c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCn5Kjp4xmOUcKk0RX6FS2UP4zgPBScI5o',
    appId: '1:448521017553:ios:ccca2cf0c826bcc434cdf0',
    messagingSenderId: '448521017553',
    projectId: 'lyne-9532c',
    storageBucket: 'lyne-9532c.appspot.com',
    iosClientId: '448521017553-uht2brqoanrf9vaatukv2c81dmvlcmhk.apps.googleusercontent.com',
    iosBundleId: 'com.example.appchat',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAvhpsw9jE5lAxAXmuOy0NwKsei8JxfXpg',
    appId: '1:448521017553:web:38b57419f7067b8634cdf0',
    messagingSenderId: '448521017553',
    projectId: 'lyne-9532c',
    authDomain: 'lyne-9532c.firebaseapp.com',
    storageBucket: 'lyne-9532c.appspot.com',
    measurementId: 'G-KJN70CR568',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCn5Kjp4xmOUcKk0RX6FS2UP4zgPBScI5o',
    appId: '1:448521017553:ios:ccca2cf0c826bcc434cdf0',
    messagingSenderId: '448521017553',
    projectId: 'lyne-9532c',
    storageBucket: 'lyne-9532c.appspot.com',
    iosClientId: '448521017553-uht2brqoanrf9vaatukv2c81dmvlcmhk.apps.googleusercontent.com',
    iosBundleId: 'com.example.appchat',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAvhpsw9jE5lAxAXmuOy0NwKsei8JxfXpg',
    appId: '1:448521017553:web:bc1eec417d7e4f1d34cdf0',
    messagingSenderId: '448521017553',
    projectId: 'lyne-9532c',
    authDomain: 'lyne-9532c.firebaseapp.com',
    storageBucket: 'lyne-9532c.appspot.com',
    measurementId: 'G-D1N86PJ98N',
  );

}